language: python

python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"

env:
  - DJANGO_VERSION=1.5.12
  - DJANGO_VERSION=1.6.11
  - DJANGO_VERSION=1.7.11
  - DJANGO_VERSION=1.8.14
  - DJANGO_VERSION=1.9.8

matrix:
  exclude:
    - python: "2.6"
      env: DJANGO_VERSION=1.7.11
    - python: "2.6"
      env: DJANGO_VERSION=1.8.14
    - python: "2.6"
      env: DJANGO_VERSION=1.9.8
    - python: "3.5"
      env: DJANGO_VERSION=1.5.12
    - python: "3.5"
      env: DJANGO_VERSION=1.6.11
    - python: "3.5"
      env: DJANGO_VERSION=1.7.11

install:
  - pip install -r requirements_test.txt
  - pip install codecov
  - pip install django==$DJANGO_VERSION

script:
  - coverage run setup.py test

after_success:
  - codecov

notifications:
  email:
    - vinta.chen@gmail.com
