language: python

python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"

env:
  - DJANGO="django>=2.0,<2.1"
  - DJANGO="django>=2.1,<2.2"
  - DJANGO="django>=2.2,<3.0"
  - DJANGO="django>=3.0,<3.1"
  - DJANGO="django>=3.1,<3.2"
  - DJANGO="django>=3.2,<3.3

matrix:
  exclude:
    - python: "3.5"
      env: DJANGO="django>=3.0"
    - python: "3.5"
      env: DJANGO="django>=3.1"
    - python: "3.8"
      env: DJANGO="django>=2.0,<2.1"
    - python: "3.8"
      env: DJANGO="django>=2.1,<2.2"

install:
  - pip install -r requirements_test.txt
  - pip install coveralls
  - pip install $DJANGO

script:
  - coverage run setup.py test

after_success:
  - coveralls

notifications:
  email:
    - vinta.chen@gmail.com
